apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app-requests-limits-deploy
  namespace: test-ns
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  minReadySeconds: 20
  selector:
    matchLabels:
      app: javawebapp
  template:
    metadata:
      name: java-app-deployment
      labels:
        app: javawebapp
    spec:
      containers:
      - name: java-app-deploy
        image: mushrifmulla/java-web-app:2
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
          limits:
            cpu: 300m
            memory: 300Mi
---
apiVersion: v1
kind: Service
metadata:
  name: javawebapp-svc
  namespace: test-ns
spec:
  type: NodePort
  selector:
    app: javawebapp
  ports:
  - port: 80
    targetPort: 9981
    nodePort: 30150
