apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-app-requests-limits-deploy
  namespace: test-ns
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  minReadySeconds: 20
  selector:
    matchLabels:
      app: mavenwebapp
  template:
    metadata:
      name: maven-app-deployment
      labels:
        app: mavenwebapp
    spec:
      containers:
      - name: maven-app-deploy
        image: mushrifmulla/maven-web-application:$TAG
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
          limits:
            cpu: 300m
            memory: 300Mi
---
apiVersion: v1
kind: Service
metadata:
  name: mavenwebapp-svc
  namespace: test-ns
spec:
  type: NodePort
  selector:
    app: mavenwebapp
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 31150
